# Generated by Django 4.0.4 on 2022-06-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Rice', 'Rice'), ('Noodles', 'Noodles'), ('Hot Dogs', 'Hot Dogs'), ('Salads', 'Salads'), ('Burgers', 'Burgers'), ('Pizza', 'Pizza'), ('Snacks', 'Snacks'), ('Sushi', 'Sushi'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks')], default=('Rice', 'Rice'), max_length=30)),
                ('cook_time', models.CharField(max_length=40)),
                ('price', models.FloatField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.food')),
            ],
        ),
    ]
