# Generated by Django 4.0.2 on 2022-05-31 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.category'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='core.Image'),
        ),
    ]
