# Generated by Django 4.0.2 on 2022-05-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_food_category_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Noodls', 'Noodles'), ('Hot Dogs', 'Hot Dogs'), ('Salads', 'Salads'), ('Burgers', 'Burgers'), ('Pizza', 'Pizza'), ('Snacks', 'Snacks'), ('Sushi', 'Sushi'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks')], default=('Rice', 'Rice'), max_length=30),
        ),
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
