# Generated by Django 4.0.2 on 2022-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_food_category_remove_food_image_food_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='food',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='food',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
