# Generated by Django 4.0.2 on 2022-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_image_food_image1_food_image2_food_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Noodles', 'Noodles'), ('Hot Dogs', 'Hot Dogs'), ('Salads', 'Salads'), ('Burgers', 'Burgers'), ('Pizza', 'Pizza'), ('Snacks', 'Snacks'), ('Sushi', 'Sushi'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks')], default=('Rice', 'Rice'), max_length=30),
        ),
    ]
