# Generated by Django 4.0.2 on 2022-05-31 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_food_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='desc',
            new_name='description',
        ),
    ]
