# Generated by Django 4.0.2 on 2022-05-31 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_desc_food_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.food')),
            ],
        ),
    ]
