# Generated by Django 4.0.4 on 2022-05-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
